# Site wide configuration

source           : .tmp/src
destination      : .tmp/dist

title            : "Sergio Forés"
description      : "Transmitir, observar, definir, hacer."
logo             : "site-logo.png"
teaser           : "default-teaser.png"
locale           : "es_ES"
words_per_minute : 200
title_separator  : "×"

repository       : "t0t/t-o-d-h.com"
url              : "http://t-o-d-h.com"

# Site owner

owner:
  name           : "Sergio Forés"
  email          :
  pinterest      : "forsraga"
  flickr         : "sergiofores"
  twitter        : "t0tinspire"
  facebook       : "sergioforesstudio"
  youtube        : "UCSsOxVck4CGhbCblzuc-gSA"
  medium         : "@todh"
  codepen        : "t0t"
  theartstack    : "sergiofores"
  linkedin       : "sergiofores"
  instagram      : "t.o.d.h"
  tumblr         : "t0tinspire"
  github         : "t0t"
  github-repo    : "https://github.com/t0t/t-o-d-h.com/"
  google:
    ad-client    : #"ca-pub-7328585512091257"
    ad-slot      : #"3049671934"
    analytics    : "UA-84536147-1"
    plus         : #"https://plus.google.com/+MichaelRoseDesign/posts"
    verify       : #"geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo"
  bing:
    verify       : #"D81F4C18A6CB3018F64D7C827D953DFD"
  alexa:
    verify       : #"Y5DYjZ4VWlrQzBP5kcQJeOKLNas"
  yandex:
    verify       : #"55a5419baf76a498"
  bio            : "Soy un papá orgulloso de sus hijos, diseñador web y front-end y en la clandestinidad inventor y artista. Residente en un pueblecito cerca de Barcelona. Trato de aportar una visión holista, integradora y coherente de la vida, el arte y el desarrollo web con el proyecto TODH."
  avatar         : "bio-photo.jpg" # 160x160 px image for author byline
staticman:
  allowedFields  : ['name', 'email', 'url', 'message']
  branch         : "master"
  commitMessage  : "New comment."
  filename       : comment-{@timestamp}
  format         : "yml"
  moderation     : true
  path           : "src/_data/comments/{options.slug}"
  requiredFields : ['name', 'email', 'message']
  transforms:
    email        : "md5"
  generatedFields:
    date:
      type       : "date"
      options:
        format   : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"


# Jekyll configuration

permalink        : /:categories/:title/
lsi              : true
future           : false
show_drafts      : false
markdown         : kramdown
kramdown:
  toc_levels     : 1..3
  input          : GFM
  hard_wrap      : false
  auto_ids       : true
  entity_output  : as_char
  smart_quotes   : lsquo,rsquo,ldquo,rdquo
  enable_coderay : false
highlighter      : rouge
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp


# Plugins

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-tagging-related_posts
  - jekyll/tagging
  - jemoji


# Collections

collections:
  faqs:
    output    : true
    permalink : /:collection/:path/
    title     : FAQs
  components:
    output    : false
  colors:
    output    : false


# Front Matter Defaults

defaults:

  # Blog Articles
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: article
      category: articles
      breadcrumbs:
        - label: "Blog Articles"
          url: /articles/

  # Mastering Paper
  # - scope:
  #     path: _posts/mastering-paper
  #     type: posts
  #   values:
  #     layout: article
  #     category: mastering-paper
  #     breadcrumbs:
  #       - label: "Mastering Paper by 53"
  #         url: /mastering-paper/

  # PaperFaces
  # - scope:
  #     path: _posts/paperfaces
  #     type: posts
  #   values:
  #     layout: article
  #     category: paperfaces
  #     breadcrumbs:
  #       - label: "PaperFaces Portraits"
  #         url: /paperfaces/
  #     comments: true

  # Procreate Paintings
  # - scope:
  #     path: _posts/procreate
  #     type: posts
  #   values:
  #     layout: article
  #     category: procreate-paintings
  #     breadcrumbs:
  #       - label: "Procreate Paintings"
  #         url: /procreate-paintings/
  #     comments: true

  # TODH
  - scope:
      path: _posts/todh
      type: posts
    values:
      layout: article
      category: todh
      breadcrumbs:
        - label: "Todh"
          url: /todh/

  # Work
  - scope:
      path: _posts/work
      type: posts
    values:
      layout: article
      category: work
      sidebar: false
      author: false
      fullwidth: true
      breadcrumbs:
        - label: "Work"
          url: /work/

  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: article
      breadcrumbs:
        - label: "Frequently Asked Questions"
          url: /faqs/
      comments: true

  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: article


# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_index
  permalinks:
    tag: /tag/:name/


# Plugin: jekyll-picture-tag

picture:
  source: "images/_originals"
  output: "images"
  markup: "picture"
  presets:
    hero:
      attr:
        class: "page__hero-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"
